### ISSUE TITLE
v4.2 --workdir fails if the directory does not contain a trailing /

### ISSUE THREAD

**Issue by nicolasDelhomme** [biocore/sortmerna#274] opened 2020-12-17 10:39 UTC
The title says it all. Since --workdir is meant for a directory it should gracefully handle cases where the trailing / is absent; something that will be a common use-case when creating directory names dynamically (such as using dirname).

ERROR: Failed writing to file: /mnt/picea/projects/.../sortmerna/P17901_124_S81_L002_sortmernasortmerna_keys_1.txt Error: Permission denied

when --workdir was /mnt/picea/projects/.../sortmerna/P17901_124_S81_L002_sortmerna

using /mnt/picea/projects/.../sortmerna/P17901_124_S81_L002_sortmerna/ solved it, but it would be nicer if it were handled in the code.

**Comment by biocodz** [comment] 2020-12-21 14:13
Thanks for reporting. I'm marking this as a bug.

**Comment by biocodz** [comment] 2021-06-02 23:07
not able to reproduce this in [v4.3.3](https://github.com/biocore/sortmerna/releases/tag/v4.3.3)

**Closed by biocodz** 2021-06-02 23:07 UTC
Labels: bug
