### ISSUE TITLE
Problem with merg script

### ISSUE THREAD

**Issue by charlesdavid** [biocore/sortmerna#116] opened 2016-04-08 15:50 UTC
Merge apparently results in broken fastq files. When combining, I noticed that the first 2 @ symbols for the sequence descriptions that are present in the R1 and R2 files were dropped in the merged file. Trying to run sortmerna on those merged files throws an error stating that the file is either empty (it is not) or not is fastq format (it basically is except for the two missing @ symbols). Why is this happening? Will the sortmerna program be unable to process a 8GB file if it is missing only the first 2 @ symbols out of billions? And critically, why is the perl script not handling large files (>6GB). Thanks

**Comment by ekopylova** [comment] 2016-04-08 15:51
Hi Charles, could you give more details about the issue you're having with the merge script? Thanks! Jenya

**Comment by charlesdavid** [comment] 2016-04-08 15:59
Was just checking some more... I just merged about 100 paired end read files using the merge script in preparation for filtering, but all of the merged files have this problem. Would really like to know how to not get the fastq format error from the program. I would prefer not to redo the merging as it took a very long time.

**Comment by ekopylova** [comment] 2016-04-08 16:01
Is the fastq error from coming sortmerna when using the merged reads? Could you paste the error here. I'll be happy to help figure out the issue ..

**Comment by charlesdavid** [comment] 2016-04-08 16:07
Yes. Here is the error:
[home]$ /software/sandbox/sortmerna/sortmerna-2.1/sortmerna --ref $SORTMERNA_DB --reads L006_MERGED.fastq --paired_in -a 8 -m 4096 --log --fastx --aligned L006_rRNA --other L006_sortmerna 
The input reads file or reference file is empty, or the reads file is not in FASTA or FASTQ format, no analysis could be made.
[home]$

**Comment by ekopylova** [comment] 2016-04-08 16:11
Could you try the same command on the first 100 reads from L006_MERGED.fastq and if the same error is thrown, would you mind e-mailing me those 100 reads?

$ head -n 400 L006_MERGED.fastq > L006_MERGED_100.fastq

**Comment by charlesdavid** [comment] 2016-04-08 16:16
Here is the problem I am having: First, the unmerged file:
[home]$ head -n L005_R1.fastq
@D00626:157:C9D2LANXX:5:2301:1096:2163 1:N:0:NGACCA
NATAAACTCCATCTTGCCATGAGTTTCTCCTTTGCTGTAAACCATTCCAAGAAAGGAGAAAAGGCTCATTCAAGTAATTGTATACACTGATAATCAAATT
+
#=ABBGGGGGGGGGGGGGGGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGC
@D00626:157:C9D2LANXX:5:2301:1215:2165 1:N:0:TGACCA
NCGAAAATCAACCGCTGCTGGTCTGGTGGAATGCCTTCCTTGTCCTGAATCTTAGCCTTGACATTGTCAATGGTGTCTGAAGACTCAACCTCTAGGGTTA
+
#<=ABFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGGGGGGGGEGGGEGGGGGGGGGGGGGGGEGGGGGGGGGGGGGGGGDGG
@D00626:157:C9D2LANXX:5:2301:1201:2246 1:N:0:TGACCA
CTGTTTCGATGAAATCAGTACCCTCATCAATAGCTCTCATGTATGCTGCTACAGTTTCTTCAGGAATTTCTCCATTTGAACCTCGGTGTGCAATGTTGTA
+
ABB0AFEGDGGE@GGGG@=FBCF>0:1FGGG1FF@BFF11<C1FEB@1@FG@G>:FG1FGEG:CGFF1CFG>GC1<FC@1>FF19BGG9EF:1F00=E0;
@D00626:157:C9D2LANXX:5:2301:1573:2155 1:N:0:TGACCA
NTGGTGGGCTAAGTCTAAGTGATTCATAAACAAATGACTGAACAAGTTCCATTTGTTTTACACTTTCAAAACTCAAATTTTCTGGCTTTGTCCCTACATT
+
#=ABBGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGEGGGGGGG
@D00626:157:C9D2LANXX:5:2301:1620:2240 1:N:0:TGACCA
TTTTAGTTCAAAAGAGGCTCAAATGTTTATGAATGAACAAGCCACTACAAACTACTTGATACAATAATCACACAAGGACCTTAAAAGAAAAACATCAGCC
+
ABBC<?BGGGBFGGGGGGGGGGFG1C11=D1>FGGGDGGG1@@FDGDGGEGDDGGGCC:ECC@BGCD>FGGGGGBB>G1<:1E1:EFGGGG0FGGC0;00

Now, the merged file after running the script:
[home]$ head -n L005_MERGED.fastq
D00626:157:C9D2LANXX:5:2301:1096:2163 1:N:0:NGACCA
NATAAACTCCATCTTGCCATGAGTTTCTCCTTTGCTGTAAACCATTCCAAGAAAGGAGAAAAGGCTCATTCAAGTAATTGTATACACTGATAATCAAATT
+
#=ABBGGGGGGGGGGGGGGGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGC
D00626:157:C9D2LANXX:5:2301:1096:2163 2:N:0:NGACCA
TGGACAGTTTCCAGGGCCACAGATTGATTGTGTGACAAATGACAATTTGATTATCAGTGTATACAATTACTTGAATGAGCCTTTTCTCCTTTCTTGGAAT
+
BCCCCGGGGGGGGGGGGBC01>1E@@:F11:1>111?F1<111E:FGGE1E11<<1:11=111:F@G>11?C<F1:1F@G@GGGG1:F1>FG0FDC000C
@D00626:157:C9D2LANXX:5:2301:1215:2165 1:N:0:TGACCA
NCGAAAATCAACCGCTGCTGGTCTGGTGGAATGCCTTCCTTGTCCTGAATCTTAGCCTTGACATTGTCAATGGTGTCTGAAGACTCAACCTCTAGGGTTA
+
#<=ABFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGGGGGGGGEGGGEGGGGGGGGGGGGGGGEGGGGGGGGGGGGGGGGDGG
@D00626:157:C9D2LANXX:5:2301:1215:2165 2:N:0:TGACCA
GGAAAAAATGCAGATCTTCGTGAAGACCCTGACGGGGAAGACTATAACCCTAGAGGTTGAGTCTTCAGACACCATTGACAATGTCAAGGCTAAGATTCAG
+
CCBCBGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFFGGGGGGGGGGGGFGGGGGGGGGGGBGGGGGCG@EGGGGGGGEGGGGGEGGG
@D00626:157:C9D2LANXX:5:2301:1201:2246 1:N:0:TGACCA
CTGTTTCGATGAAATCAGTACCCTCATCAATAGCTCTCATGTATGCTGCTACAGTTTCTTCAGGAATTTCTCCATTTGAACCTCGGTGTGCAATGTTGTA
+
ABB0AFEGDGGE@GGGG@=FBCF>0:1FGGG1FF@BFF11<C1FEB@1@FG@G>:FG1FGEG:CGFF1CFG>GC1<FC@1>FF19BGG9EF:1F00=E0;
[home]$
Notice how the first two @ symbols have been dropped?
Is this causing the whole program to choke?

**Comment by charlesdavid** [comment] 2016-04-08 16:23
As requested, just tried the short file and got the same error:

[home]$ /software/sandbox/sortmerna/sortmerna-2.1/sortmerna --ref $SORTMERNA_DB --reads Short_MERGED.fastq --paired_in -a 8 -m 4096 --log --fastx --aligned Short_rRNA --other Short_sortmerna
  The input reads file or reference file is empty, or the reads file is not in FASTA or FASTQ format, no analysis could be made.
[home]$

**Comment by ekopylova** [comment] 2016-04-08 16:27
Yes, the fastq files require to start with '@' and an error ill be thrown otherwise.
I'm not sure why that first '@' is being removed from your merged file. I just tried the merge command on the 5 reads (R1) you've pasted together with an R2 file including the same 5 reads except with 1:N:0: being 2:N:0 and the output is as expected. Could you try the merge script on the first 100 reads from both forward and reverse files and see if the '@' is removed again?

$ bash /sortmerna-2.1/scripts/merge-paired-reads.sh R1.fastq R2.fastq merged.fastq

What perl script are you referring to in your initial program description? Sortmerna is written in C/C++ and the merge scripts in bash.

Thanks!

**Comment by charlesdavid** [comment] 2016-04-08 16:30
Yes, I have done that when evaluating this program. It worked fine on small files. When I tried to do my actual experiment, it failed with this error. I need this merge to work with files that are about 5 GB each, so 10 GB total, with billions of reads.

**Comment by charlesdavid** [comment] 2016-04-08 16:30
How to override this issue to use the MERGED files with missing @ symbols?

**Comment by charlesdavid** [comment] 2016-04-08 16:35
My reference to Perl came from the scripts themselves:
##### merge the files
echo "   Processing $1 .."
perl -pe 's/\n/\t/ if $. %4' $1 > $3.READS1
echo "   Processing $2 .."
perl -pe 's/\n/\t/ if $. %4' $2 > $3.READS2
echo "   Interleaving $1 and $2 .."
paste -d '\n' $3.READS1 $3.READS2 | tr "\t" "\n" > $3

**Comment by ekopylova** [comment] 2016-04-08 16:44
The best solution would be to update the merged files to include the '@' symbol. Even if the code to throw this error is silenced, sortmerna will have issues later on to correctly parse the file in memory which will require the knowledge of all '@'. If you're not sure how to do that, I can give you the commands but will have to be later in the day. Also, I would suggest running a FASTQ validating script on your merged files to verify it's correct (e.g.. FastQValidator). Are both your R1 and R2 files 4GB each? This error has never been reported to me before so I would like to find the underlying issue but again won't have a chance to look at it until later today.

**Comment by charlesdavid** [comment] 2016-04-08 16:53
Well, this seems at least consistently annoying: It seems like every merged file on the cluster has missing @ symbols for the first two sequences. I do not know if there are more dropped internally, but the repeating the short_merged test using the tail -n 400 worked fine. And as I said earlier, it always worked before with smaller files. The production files are quite large, about 4-5GB each, so 8-10 GB when combined. I would really like to know what is happening here... Thanks for checking it out.

**Comment by charlesdavid** [comment] 2016-04-09 11:29
Debug update: I have been running some tests in the HPCC environment and it looks like the issue may be linked to the use of process substitution when running the merge script. The command in the bash script looks like this: ${SMRNA}/scripts/merge-paired-reads.sh <(zcat $file1) <(zcat $file2) ${OUT}/${NAME}_MERGED.fastq and for some reason that I can not fathom, when this runs the @ symbols of the first two reads (lines 1 and 5) in the merged fastq are dropped. This occurs irrespective of size, even when using the test case of 100 sequences. The mystery now is why it is only those two @ symbols dropped... I have verified that if the gz files are manually decompressed first then the Perl works as expected. If you have any ideas regarding the gremlin that likes to eat the @ symbols, I would love to hear them. Please consider integrating the ability to take the two F/R files in your upcoming release for PE mode, as well as adding support for compressed files. It is really not a data management best practice to have to unzip all the raw data files and then double it again for the merge... at least our IT department grumbles about this clogging of the cluster resources. Thanks again for any follow up thoughts.

**Comment by ekopylova** [comment] 2016-04-14 16:09
Hi Charles,

Discussing with a collaborator who helped write the merge script, we don't think >4GB files should be an issue on any 64bits computer and the issue may be specific to your environment and use of an HPCC. What type of OS, scheduler and GZIP library is your HPCC using and are any pre- or post- jobs done when you submit your data? Also, knowing how you proceed with different steps (unzipping, merging, etc.) would be helpful to locate the issue. As the problem is not directly with SortMeRNA and I cannot reproduce it on our own systems, it may be easier/faster to use another method of merging/unmerging the files.

Regarding support for GZIP files, that is planned to be merged into the master code (see [PR](https://github.com/biocore/sortmerna/pull/111)) when I get the time to finalize installation code (very busy with other projects at the moment). That PR also supports an alternative method to read input files which will allow for easy integration of forward/reverse reading (though scheduled for another PR).

Sorry for the inconvenience, 
Jenya

**Closed** 2016-12-06 11:26 UTC
