### ISSUE TITLE
Erroneous CIGAR string and alignment coordinates

### ISSUE THREAD

**Issue by jftaly** [biocore/sortmerna#72] opened 2015-03-18 17:00 UTC
Thanks a lot for this tool, it is very usefull for my work.
Basically, I am using it for filtering sequences and cutting them to the boundaries defined by the alignment of sortmerna.
Unfortunately, I encountered an error about the CIGAR strings in the sam/blast output.

Briefly, a sequence, embedded in this message, of 1487bp is correctly detected as to be 16s RRNA but is aligned from positions 58 to 1491 (after the true end of the sequence).

The CIGAR string seems erroneous (ending by 4294967292S):
57S57M2I12M2D4M2I29M1D11M2I3M2D11M1I7M1D13M5D4M3D9M2D3M7D1264M4294967292S

Without the opening 57S the boundaries would have been correct I guess.

I am using the version '2.0, 29/11/2014' of the linux 64 binaries and the following command lines:
indexdb_rna --ref silva-bac-16s-id90.fasta,silva-bac-16s-id90.idx
sortmerna --ref silva-bac-16s-id90.fasta,silva-bac-16s-id90.idx --reads AB271211.fna --sam --SQ --blast 3 --aligned AB271211-sortmerna --log

Am I doing something wrong? Could you please help me on this issue?
Let me know if you need more input from my part.

Thanks a lot

Best

Jean-François

>AB271211               1487 residues
TCCAACGCGTTGGGAGCTCTCCCATATGGTCGACCTGCAGGCGGCCGCACTAGTGATTAG
AGTTTGATCCTGGCTCAGGATGAACGCTGGCGGCGTGCCTAACACATGCAAGTCGAACGG
GAATCTTCGGATTCTAGTGGCGGACGGGTGAGTAACGCGTAAGAATCTAACTTCAGGACG
GGGACAACAGTGGGAAACGACTGCTAATACCCGATGTGCCGCGAGGTGAAACCTAATTGG
CCTGAAGAGGAGCTTGCGTCTGATTAGCTAGTTGGTGGGGTAAGAGCCTACCAAGGCGAC
GATCAGTAGCTGGTCTGAGAGGATGAGCAGCCACACTGGGACTGAGACACGGCCCAGACT
CCTACGGGAGGCAGCAGTGGGGAATTTTCCGCAATGGGCGAAAGCCTGACGGAGCAACGC
CGCGTGAGGGAGGAAGGTCTTTGGATTGTAAACCTCTTTTCTCAAGGAAGAAGTTCTGAC
GGTACTTGAGGAATCAGCCTCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGGGGAG
GCAAGCGTTATCCGGAATTATTGGGCGTAAAGCGTCCGCAGGTGGTCAGCCAAGTCTGCC
GTCAAATCAGGTTGCTTAACGACCTAAAGGCGGTGGAAACTGGCAGACTAGAGAGCAGTA
GGGGTAGCAGGAATTCCCAGTGTAGCGGTGAAATGCGTAGAGATTGGGAAGAACATCGGT
GGCGAAAGCGTGCTACTGGGCTGTATCTGACACTCAGGGACGAAAGCTAGGGGAGCGAAA
GGGATTAGATACCCCTGTAGTCCTAGCCGTAAACGATGGATACTAGGCGTGGCTTGTATC
GACCCGAGCCGTGCCGAAGCTAACGCGTTAAGTATCCCGCCTGGGGAGTACGCACGCAAG
TGTGAAACTCAAAGGAATTGACGGGGGCCCGCACAAGCGGTGGAGTATGTGGTTTAATTC
GATGCAACGCGAAGAACCTTACCAAGACTTGACATGTCGCGAACCCTGGTGAAAGCTGGG
GGTGCCTTCGGGAGCGCGAACACAGGTGGTGCATGGCTGTCGTCAGCTCGTGTCGTGAGA
TGTTGGGTTAAGTCCCGCAACGAGCGCAACCCTCGTTCTTAGTTGCCAGCATTAAGTTGG
GGACTCTAAGGAGACTGCCGGTGACAAACCGGAGGAAGGTGGGGATGACGTCAAGTCAGC
ATGCCCCTTACGTCTTGGGCGACACACGTACTACAATGGTCGGGACAAAGGGCAGCGAAC
TTGCGAGAGCCAGCGAATCCCAGCAAACCCGGCCTCAGTTCAGATTGCAGGCTGCAACTC
GCCTGCATGAAGGAGGAATCGCTAGTAATCGCCGGTCAGCATACGGCGGTGAATTCGTTC
CCGGGCCTTGTACACACCGCCCGTCACACCATGGAAGCTGGTCACGCCCGAAGTCATTAC
CTCAACCGCAAGGAGGGGGATGCCTAAGGCAGGGCTAGTGACTGGGG

**Comment by ekopylova** [comment] 2015-03-18 19:59
Hi Jean-François,

You're right, there appears to be an error generating the CIGAR string (I was able to reproduce it with your example, thanks!). I'll take a look at the issue shortly and report back once it's fixed.

Jenya

**Comment by jftaly** [comment] 2015-03-19 08:33
Thanks a lot Jenya,

May I ask if it would be feasible for you to add in the blast output a column for the field  "Subject Strand". It would be very usefull to me.

Thanks again.

JF

**Comment by ekopylova** [comment] 2015-03-21 00:10
Hi Jean-François,

I've found the error in the code and fixed it (had to do with computing a longer alignment length than necessary, resulting in an overflow), as well I modified the `--blast INT` option to `--blast STRING` to accommodate other fields in the -m 8 output. After one of the co-authors reviews this [PR](https://github.com/biocore/sortmerna/pull/74/files), I'll merge it to the development version.

Now, the CIGAR string is ```57S57M2I12M2D4M2I29M1D11M2I3M2D11M1I7M1D13M5D4M3D9M2D3M7D1260M``` with the alignment illustrated below (`--blast '0'` option). I've also modified the `--blast` parameter to accept a string rather than integer. The string can be '0' for human-readable format and '1' for standard Blast-like m8 format. Three additional columns are supported with `--blast '1'` which are `cigar, qcov and qstrand`. To output the query strand (sortmerna reverse-complements the queries for searches), you can call `--blast '1 qstrand'`. The order of the additional columns does not matter, so you can call `--blast '1 qstrand qcov'` or `--blast '1 qcov qstrand'`. 

```
Sequence ID: Unc49508 count=1; cluster_weight=4; cluster=Unc49508; cluster_score=1.000000; cluster_center=True; 
Query ID: AB271211 1487 residues
Score: 2430 bits (2113)	Expect: 0	strand: +

Target:        1    TAGAGTTTGATCCTGGCTCAGGACGAACGCTGGCGGCGTGCTTAACACATGCAAGTC--A    58
                    |||||||||||||||||||||||*|||||||||||||||||*|||||||||||||||  |
Query:        58    TAGAGTTTGATCCTGGCTCAGGATGAACGCTGGCGGCGTGCCTAACACATGCAAGTCGAA    117

Target:       59    CGGGGGCCCGCAAGGGT--AACCGGCGAACGGGTGCGTAACACGTGAGCAATCTGCCGTC    116
                    ||||***|**|  ||*|  *|**||||*|||||||*|||||*|||*|| |||||**|*||
Query:       118    CGGGAATCTTC--GGATTCTAGTGGCGGACGGGTGAGTAACGCGTAAG-AATCTAACTTC    174

Target:      117    --CACTGGGGGATAGCCG-GCCCAACGGCCGGGTAATACCGCATACGTTCCCTTGCCGGC    173
                      *||  |||||*|*|*| |***||| |*|*|*|||||||     ||*|   *|||||**
Query:       175    AGGAC--GGGGACAACAGTGGGAAAC-GACTGCTAATACC-----CGAT---GTGCCGCG    223

Target:      174    ATCGGTGGGGGAGGAAACCTCCGGGGGTGGACGAGGAGCTCGCGGCCTATCAGCTAGTTG    233
                    |  |||       |||||||****||***||*||||||||*|||*|**||*|||||||||
Query:       224    A--GGT-------GAAACCTAATTGGCCTGAAGAGGAGCTTGCGTCTGATTAGCTAGTTG    274

Target:      234    GTGGGGTCACGGCCTACCAAGGCGATGACGGGTAGCTGGTCTGAGAGGATGGCCAGCCAC    293
                    |||||||*|**||||||||||||||*||***||||||||||||||||||||**|||||||
Query:       275    GTGGGGTAAGAGCCTACCAAGGCGACGATCAGTAGCTGGTCTGAGAGGATGAGCAGCCAC    334

Target:      294    ATTGGGACTGAGATACGGCCCAGACTCCTACGGGAGGCAGCAGTGGGGAATATTGCGCAA    353
                    |*|||||||||||*|||||||||||||||||||||||||||||||||||||*||*|||||
Query:       335    ACTGGGACTGAGACACGGCCCAGACTCCTACGGGAGGCAGCAGTGGGGAATTTTCCGCAA    394

Target:      354    TGGCCGCAAGGCTGACGCAGCGACGCCGCGTGAGGGAGGAAGGTCTTTGGATTGTAAACC    413
                    |||*||*|||*||||||*|||*||||||||||||||||||||||||||||||||||||||
Query:       395    TGGGCGAAAGCCTGACGGAGCAACGCCGCGTGAGGGAGGAAGGTCTTTGGATTGTAAACC    454

Target:      414    TCTTTTCTCAAGGAAGAAGTTCTGACGGTACTTGAGGAATCAGCCTCGGCTAACTCCGTG    473
                    ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Query:       455    TCTTTTCTCAAGGAAGAAGTTCTGACGGTACTTGAGGAATCAGCCTCGGCTAACTCCGTG    514

Target:      474    CCAGCAGCCGCGGTAATACGGGGGAGGCAAGCGTTATCCGGAATTATTGGGCGTAAAGCG    533
                    ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Query:       515    CCAGCAGCCGCGGTAATACGGGGGAGGCAAGCGTTATCCGGAATTATTGGGCGTAAAGCG    574

Target:      534    TCCGCAGGTGGTCAGCCAAGTCTGCCGTCAAATCAGGTTGCTTAACGACCTAAAGGCGGT    593
                    ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Query:       575    TCCGCAGGTGGTCAGCCAAGTCTGCCGTCAAATCAGGTTGCTTAACGACCTAAAGGCGGT    634

Target:      594    GGAAACTGGCAGACTAGAGAGCAGTAGGGGTAGCAGGAATTCCCAGTGTAGCGGTGAAAT    653
                    ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Query:       635    GGAAACTGGCAGACTAGAGAGCAGTAGGGGTAGCAGGAATTCCCAGTGTAGCGGTGAAAT    694

Target:      654    GCGTAGAGATTGGGAAGAACATCGGTGGCGAAAGCGTGCTACTGGGCTGTATCTGACACT    713
                    ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Query:       695    GCGTAGAGATTGGGAAGAACATCGGTGGCGAAAGCGTGCTACTGGGCTGTATCTGACACT    754

Target:      714    CAGGGACGAAAGCTAGGGGAGCGAAAGGGATTAGATACCCCTGTAGTCCTAGCCGTAAAC    773
                    ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Query:       755    CAGGGACGAAAGCTAGGGGAGCGAAAGGGATTAGATACCCCTGTAGTCCTAGCCGTAAAC    814

Target:      774    GATGGATACTAGGCGTGGCTTGTATCGACCCGAGCCGTGCCGAAGCTAACGCGTTAAGTA    833
                    ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Query:       815    GATGGATACTAGGCGTGGCTTGTATCGACCCGAGCCGTGCCGAAGCTAACGCGTTAAGTA    874

Target:      834    TCCCGCCTGGGGAGTACGCACGCAAGTGTGAAACTCAAAGGAATTGACGGGGGCCCGCAC    893
                    ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Query:       875    TCCCGCCTGGGGAGTACGCACGCAAGTGTGAAACTCAAAGGAATTGACGGGGGCCCGCAC    934

Target:      894    AAGCGGTGGAGTATGTGGTTTAATTCGATGCAACGCGAAGAACCTTACCAAGACTTGACA    953
                    ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Query:       935    AAGCGGTGGAGTATGTGGTTTAATTCGATGCAACGCGAAGAACCTTACCAAGACTTGACA    994

Target:      954    TGTCGCGAACCCTGGTGAAAGCTGGGGGTGCCTTCGGGAGCGCGAACACAGGTGGTGCAT    1013
                    ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Query:       995    TGTCGCGAACCCTGGTGAAAGCTGGGGGTGCCTTCGGGAGCGCGAACACAGGTGGTGCAT    1054

Target:     1014    GGCTGTCGTCAGCTCGTGTCGTGAGATGTTGGGTTAAGTCCCGCAACGAGCGCAACCCTC    1073
                    ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Query:      1055    GGCTGTCGTCAGCTCGTGTCGTGAGATGTTGGGTTAAGTCCCGCAACGAGCGCAACCCTC    1114

Target:     1074    GTTCTTAGTTGCCAGCATTAAGTTGGGGACTCTAAGGAGACTGCCGGTGACAAACCGGAG    1133
                    ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Query:      1115    GTTCTTAGTTGCCAGCATTAAGTTGGGGACTCTAAGGAGACTGCCGGTGACAAACCGGAG    1174

Target:     1134    GAAGGTGGGGATGACGTCAAGTCAGCATGCCCCTTACGTCTTGGGCGACACACGTACTAC    1193
                    ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Query:      1175    GAAGGTGGGGATGACGTCAAGTCAGCATGCCCCTTACGTCTTGGGCGACACACGTACTAC    1234

Target:     1194    AATGGTCGGGACAAAGGGCAGCGAACTCGCGAGAGCCAGCGAATCCCAGCAAACCCGGCC    1253
                    |||||||||||||||||||||||||||*||||||||||||||||||||||||||||||||
Query:      1235    AATGGTCGGGACAAAGGGCAGCGAACTTGCGAGAGCCAGCGAATCCCAGCAAACCCGGCC    1294

Target:     1254    TCAGTTCAGATTGCAGGCTGCAACTCGCCTGCATGAAGGAGGAATCGCTAGTAATCGCCG    1313
                    ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Query:      1295    TCAGTTCAGATTGCAGGCTGCAACTCGCCTGCATGAAGGAGGAATCGCTAGTAATCGCCG    1354

Target:     1314    GTCAGCATACGGCGGTGAATTCGTTCCCGGGCCTTGTACACACCGCCCGTCACACCATGG    1373
                    ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Query:      1355    GTCAGCATACGGCGGTGAATTCGTTCCCGGGCCTTGTACACACCGCCCGTCACACCATGG    1414

Target:     1374    AAGCTGGTCACGCCCGAAGTCATTACCTCAACCGCAAGGAGGGGGATGCCTAAGGCAGGG    1433
                    ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Query:      1415    AAGCTGGTCACGCCCGAAGTCATTACCTCAACCGCAAGGAGGGGGATGCCTAAGGCAGGG    1474

Target:     1434    CTAGTGACTGGGG    1446
                    |||||||||||||
Query:      1475    CTAGTGACTGGGG    1487
```

**Comment by jftaly** [comment] 2015-03-23 08:30
Great!
Thanks a lot.
Please let me know when I ca pull the new version.
Best regards
JF

**Comment by ekopylova** [comment] 2015-03-24 14:10
Hi Jean-François,
I merged the PR, please try out the new code (master branch) and let me know if the issue is fixed from your end. Thanks!
Jenya

**Comment by jftaly** [comment] 2015-03-24 16:43
Dear Jenya,
After a few checks, it seems that everything is fine. In the next days I will use intensively sortmerna and I'll let you know if I encounter an additional issue.

Thanks a lot for your help, I very much appreciate your fast answers.

Best wishes

Jean-François

**Closed** 2015-04-13 20:59 UTC
