### ISSUE TITLE
Empty line in fastq file and wrong sequence quality

### ISSUE THREAD

**Issue by cpaysan** [biocore/sortmerna#117] opened 2016-08-11 08:19 UTC
Hello, 
I use SortMeRNA in a pipeline to pre-process RNA-Seq data. SortMeRNA is used to remove ribosomal RNA (rRNA) contamination. SortMeRNA is used after the trimming of the reads with Trimmomatic. When I used SortMeRNA to filter PE fastq files,  I have had spurious empty line occurring in the fastq files created using --fastx --other --paired_in using multithreading. I have had also quality sequence of read 1 in fastq file of the read 2 and quality sequence of read 2 in the fastq file of the read 1. The bug happened for one sample in around 10 samples analysed. 
The next figures explains the bug I see. (in attach file)

[figures_bug_emptyLine_wrongQuality_inPEFastqFiles.docx](https://github.com/biocore/sortmerna/files/412765/figures_bug_emptyLine_wrongQuality_inPEFastqFiles.docx)

The first figure is an extract of my Reads 2 fastq file created with Trimmomatic. 
The second figure is an extract of my Reads 1 fastq file after filtering with SortMeRNA. I have an empty line before the first line of the read named @NB501040:2:HGVWFBGXX:4:23409:20850:18142 1:N:0:ACAGTG. This is the line number 192 967 553 in this fastq file. The quality sequence of this read and next reads is the quality of the corresponding read 2 (coloured in red).
The third figure is an extract of my Reads 1  fastq file created with Trimmomatic. 
The fourth figure is an extract of my Reads 2 fastq file after filtering with SortMeRNA.
Line number 192 967 553 has quality line of the next read
Quality SortMeRNA/R2 read = Quality Trimmomatic/R1 of the next read (read +1)

I used these commands :+1: 
to create the merged file : 
bash /usr/local/bio/sortmerna/scripts/merge-paired-reads.sh /data/POPS/NGS2015_LeafNet2_NextSeq500test/Preprocessing/Trimmomatic/Trimmomatic_Quality/No-DexCyclo_3_S2_ARandQualtrimPaired_R1_001.fastq /data/POPS/NGS2015_LeafNet2_NextSeq500test/Preprocessing/Trimmomatic/Trimmomatic_Quality/No-DexCyclo_3_S2_ARandQualtrimPaired_R2_001.fastq /data/POPS/NGS2015_LeafNet2_NextSeq500test/Preprocessing/SortMeRNA/No-DexCyclo_3_S2_merged_reads.fastq

to filter rRNA : 
/usr/local/bio/sortmerna/bin/sortmerna --ref /usr/local/bio/sortmerna/rRNA_databases/silva-bac-16s-id90.fasta,/usr/local/bio/sortmerna/rRNA_databases/index/silva-bac-16s-db:\
/usr/local/bio/sortmerna/rRNA_databases/silva-bac-23s-id98.fasta,/usr/local/bio/sortmerna/rRNA_databases/index/silva-bac-23s-db:\
/usr/local/bio/sortmerna/rRNA_databases/silva-arc-16s-id95.fasta,/usr/local/bio/sortmerna/rRNA_databases/index/silva-arc-16s-db:\
/usr/local/bio/sortmerna/rRNA_databases/silva-arc-23s-id98.fasta,/usr/local/bio/sortmerna/rRNA_databases/index/silva-arc-23s-db:\
/usr/local/bio/sortmerna/rRNA_databases/silva-euk-18s-id95.fasta,/usr/local/bio/sortmerna/rRNA_databases/index/silva-euk-18s-db:\
/usr/local/bio/sortmerna/rRNA_databases/silva-euk-28s-id98.fasta,/usr/local/bio/sortmerna/rRNA_databases/index/silva-euk-28s-db:\
/usr/local/bio/sortmerna/rRNA_databases/rfam-5s-database-id98.fasta,/usr/local/bio/sortmerna/rRNA_databases/index/rfam-5s-db:\
/usr/local/bio/sortmerna/rRNA_databases/rfam-5.8s-database-id98.fasta,/usr/local/bio/sortmerna/rRNA_databases/index/rfam-5.8s-db\
 --reads /data/POPS/NGS2015_LeafNet2_NextSeq500test/Preprocessing/SortMeRNA/No-DexCyclo_3_S2_merged_reads.fastq --aligned /data/POPS/NGS2015_LeafNet2_NextSeq500test/Preprocessing/SortMeRNA/No-DexCyclo_3_S2_ribo_clean --other /data/POPS/NGS2015_LeafNet2_NextSeq500test/Preprocessing/SortMeRNA/No-DexCyclo_3_S2_noribo_clean --fastx --log  --num_alignments 1 --paired_in -a 8 -v

The first lines writed by SortMeRNA : 
Program:     SortMeRNA version 2.1, 01/02/2016
  Copyright:   2012-16 Bonsai Bioinformatics Research Group:
               LIFL, University Lille 1, CNRS UMR 8022, INRIA Nord-Europe
               2014-16 Knight Lab, Department of Pediatrics, UCSD, La Jolla,
  Disclaimer:  SortMeRNA comes with ABSOLUTELY NO WARRANTY; without even the
               implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
               See the GNU Lesser General Public License for more details.
  Contact:     Evguenia Kopylova, jenya.kopylov@gmail.com 
               Laurent Noé, laurent.noe@lifl.fr
               Hélène Touzet, helene.touzet@lifl.fr

  Computing read file statistics ... done [139.98 sec]
  size of reads file: 21062017246 bytes
  partial section(s) to be executed: 20 of size 1073741824 bytes 
  Parameters summary:
    Number of seeds = 2
    Edges = 4 (as integer)
    SW match = 2
    SW mismatch = -3
    SW gap open penalty = 5
    SW gap extend penalty = 2
    SW ambiguous nucleotide = -3
    SQ tags are not output
    Number of threads = 8

I worked on Debian
Description:    Debian GNU/Linux 8.5 (jessie)
Release:    8.5
Codename:   jessie

Let me know if you need any more infos. I could you send my fastq files if you want.

Christine Paysant-Le Roux
Equipe Genomic Networks (Gnet)
Paris-Saclay Institute of Plant Sciences (IPS2)
UMR 1403 INRA-CNRS-UPSud-UP7-UEVE
bât. 630, rue Noetzlin 
91405 ORSAY Cedex – FRANCE

**Comment by ekopylova** [comment] 2016-08-23 05:47
Hi Jessie,

Thank you for reporting this bug!

I apologize for the delayed reply, starting September I'll have more time to devote to SortMeRNA.

Yes, if you could send me your FASTQ files that would be the easiest way for me to locate and fix the issue. Please use jenya.kopylov @ gmail dot com.

Jenya

**Comment by sunitj** [comment] 2017-05-16 17:49
Just checking in to see if this was ever resolved?

**Comment by pjongeneel** [comment] 2017-05-16 18:21
i'd like to know too. Am using 2.0 (havent upgraded to 2.1) but it wasnt in the release notes anyways.

**Comment by Bernadetadad** [comment] 2017-06-07 11:27
I'd like to report the same issue

**Comment by ekopylova** [comment] 2017-06-09 11:10
To inform everyone, we have found the issue and working on a solution now. Until we release the next version, you can either specify a larger ```-m``` value (e.g., double the default) if using an existing release, or use the default I/O implemented in the development version (which will require the entire FASTA/FASTQ file to be loaded into RAM).

**Comment by mariatraka** [comment] 2017-06-26 14:15
I have exactly the same problem and I'll now try to increase -m to max (just to be sure). Hope it works!!!

**Comment by mariatraka** [comment] 2017-06-27 13:52
I have exactly the same problem. 6 out of 115 samples are throwing errors (empty lines) even though the default is the maximum (default: m = 235497). I have rerun the sortmerna for just the 6 and this time it worked for 4 out of them. The remaining 2 i have removed the empty lines and they seem to work fine downstream. 
ekopylova, can you please comment whether a simple removal of the empty line is sufficient?
Thanks!

**Comment by cpaysan** [comment] 2017-06-28 06:33
yes, we remove the empty line in the fastq file generated by SortMeRNA (in the merged-reads.fastq from SortMeRNA if PE sequencing) and it is sufficient.


Christine


**********************************************************************************
* Attention nouvelle adresse email : christine.paysant-le-roux@inra.fr  *
**********************************************************************************

Christine Paysant - Le Roux
Equipe Genomic Networks (Gnet)
Paris-Saclay Institute of Plant Sciences (IPS2)
UMR 1403 INRA-CNRS-UPSud-UP7-UEVE
bâtiment 630 Plateau du moulon
rue Noetzlin
CS 80004
91192 GIF SUR YVETTE cedex


http://www.ips2.u-psud.fr
bureau 1.82
(33) 1 69 15 75 89

________________________________
De : mariatraka <notifications@github.com>
Envoyé : mardi 27 juin 2017 16:52
À : biocore/sortmerna
Cc : cpaysan; Author
Objet : Re: [biocore/sortmerna] Empty line in fastq file and wrong sequence quality (#117)


I have exactly the same problem. 6 out of 115 samples are throwing errors (empty lines) even though the default is the maximum (default: m = 235497). I have rerun the sortmerna for just the 6 and this time it worked for 4 out of them. The remaining 2 i have removed the empty lines and they seem to work fine downstream.
ekopylova, can you please comment whether a simple removal of the empty line is sufficient?
Thanks!

-

**Comment by ekopylova** [comment] 2017-06-28 08:13
Hello,

Yes you can remove the newline and it should work. However, we are working on the next release and this issue will be fixed. Apologies for the delays, it's been a very busy period.

Best,
Jenya

**Comment by mariatraka** [comment] 2017-06-28 08:44
Thanks Jenya!
The next step worked fine (trim_galore) so seems to have worked.
Thanks,
Maria

MARIA TRAKA, PhD, MSc
Senior Research Scientist
Food and Health Programme

Quadram Institute Bioscience,
Norwich Research Park, NR4 7UA

T:  +44 (0)1603 255000
D:  +44 (0)1603 255194
maria.traka@quadram.ac.uk<mailto:maria.traka@quadram.ac.uk>
www.quadram.ac.uk<http://www.quadram.ac.uk/>

[cid:image001.png@01D2BDD9.CD461200]

Institute of Food Research has transformed into the Quadram Institute Bioscience as the first step to realising the vision of the Quadram Institute, due to open mid 2018.

**Comment by mariatraka** [comment] 2017-06-28 09:06
Thanks Christine! The next step seems to work fine so problem solved! Maria

Maria Traka, PhD
Senior Research Scientist
Chair of the Athena SWAN SAT
Food and Health Programme
Institute of Food Research
Tel: +44(0) 1603 255194

**Comment by mabentley86** [comment] 2018-01-15 16:17
Any update on when a fix for this will be released please?

**Comment by stellaartois15** [comment] 2018-01-15 20:55
Hi @mabentley86,

We are currently testing the next release. We expect an alpha-release 2.2 for February 2018.

**Comment by ekopylova** [comment] 2018-01-16 14:02
Hello @mabentley86,

As we are testing, any new examples would be great to add. Would you have a small example that reproduces this issue? You can e-mail me all necessary files at jenya . kopylov [at] gmail [dot] com . Thanks.

**Comment by ekopylova** [comment] 2018-11-30 09:42
Release [v.3.0.2](https://github.com/biocore/sortmerna/releases/tag/v3.0.2) implements a completely new I/O method and this problem should be resolved.

**Closed by ekopylova** 2018-11-30 09:42 UTC
