### ISSUE TITLE
Issue #174 in Ubuntu 16.04

### ISSUE THREAD

**Issue by OnlyHigh** [biocore/sortmerna#185] opened 2019-02-21 23:41 UTC
Hello, 
I got the following error related to issue #174:
```
bio@biocomp04:~/Documents/MyThesis/mtDNA_Recovery/sortmerna/mtDNA-recovery$ sortmerna --ref databases/16s-al.fa,16s --reads UdeA-interleaved.fq --aligned 16s --fastx --paired_in --sam --threads 4
test_kvdb_path: Key-value DB location was not specified. Setting default
test_kvdb_path: Using Key-value DB location: /home/bio/kvdb
dirExists: Path does not exist: /home/bio/kvdb
test_kvdb_path: Directory /home/bio/kvdb does not exists - will attempt to createmain:55 Running task ALIGN_REPORT: 4
```
My version of sortmerna is the following:
bio@biocomp04:~/Documents/MyThesis/mtDNA_Recovery/sortmerna/mtDNA-recovery$ sortmerna --version
```
SortMeRNA version 3.0.3
Build Date: Jan 16 2019
sortmerna_build_git_sha:@9cd1ad1f27192a1aa3597aa2428db267f62f5081@
sortmerna_build_git_date:@2019/01/16 20:48:18@
```

How can I fix it? 
Cheers, 
Luis Alfonso.

**Comment by biocodz** [comment] 2019-02-22 14:44
Form the description I don't quite understand what the problem is. Are you getting a segfault? Or does the execution hangs after printing `...Running task ALIGN_REPORT: 4`?

**Comment by OnlyHigh** [comment] 2019-02-22 15:02
Sorry for that. 
The execution hangs after printing ```...Running task ALIGN_REPORT: 4```

**Comment by biocodz** [comment] 2019-02-22 15:08
Did you use a release to install the software or build it yourself?
What's the output of `ls -lrta /home/bio/kvdb`?

**Comment by OnlyHigh** [comment] 2019-02-25 16:54
This is the output:
```
bio@biocomp04:~/Documents/MyThesis$ ls -lrta /home/bio/kvdb
ls: cannot access '/home/bio/kvdb': No such file or directory
```
I used a release, 
PS, I'll try full paths

**Comment by remondulos** [comment] 2019-03-26 15:09
Is there already a fix for this? I have the same problem on Ubuntu 18.04 with sortmerna 3.0.3 (installed release 3.0.3 from Github):
```
test_kvdb_path: Using Key-value DB location: /data/dulosr/kvdb/
dirExists: Path is a directory: /data/dulosr/kvdb/
dirExists: Path is a directory: /data/dulosr/kvdb/
list_dir:57 Directory /data/dulosr/kvdb/ has 18 files
test_kvdb_path: Directory /data/dulosr/kvdb/ exists and is Not empty. Please, make sure the directory is empty, or specify a different directory using option '-d'
```

**Comment by biocodz** [comment] 2019-03-26 18:31
This is an unrelated bug. Sortmerna needs the directory `/data/dulosr/kvdb/` to be empty, exactly as it says.

**Comment by remondulos** [comment] 2019-03-27 07:57
So I have to remove the kvdb folder everytime I want to run sortmerna? I used to run sortmerna 2.1 (on an older system) and there I had no such problems.

**Comment by biocodz** [comment] 2019-03-27 12:18
Yep, sortmerna changed quite a bit since release 2. You can check the highlights here [Release 3](https://github.com/biocore/sortmerna/releases/tag/v3.0.0). `kvdb` didn't exist in 2.0. This is a temporary directory used by SMR internally for storing alignment results. This folder has to be manually cleaned-up prior each new run, and [Issue 171](https://github.com/biocore/sortmerna/issues/171) is the reason why it's not done automatically.

**Comment by biocodz** [comment] 2019-10-17 13:22
Closing for inactivity

**Closed by biocodz** 2019-10-17 13:22 UTC
